/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'serverId' : IDL.Text,
});
export const Server = IDL.Record({
  'id' : IDL.Text,
  'ip' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'rating' : IDL.Nat,
  'ytVideoUrl' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'discordUrl' : IDL.Opt(IDL.Text),
  'version' : IDL.Opt(IDL.Text),
  'maxPlayers' : IDL.Opt(IDL.Nat),
  'location' : IDL.Opt(IDL.Text),
  'gameMode' : IDL.Opt(IDL.Text),
  'status' : IDL.Opt(IDL.Text),
});
export const SiteSettings = IDL.Record({ 'heroSubtitle' : IDL.Text });

export const idlService = IDL.Service({
  'addReview' : IDL.Func([Review], [], []),
  'addServer' : IDL.Func([Server], [], []),
  'deleteReview' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteServer' : IDL.Func([IDL.Text], [], []),
  'getAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
  'getLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'saveSiteSettings' : IDL.Func([SiteSettings], [], []),
  'seedSampleServers' : IDL.Func([], [], []),
  'setAnnouncement' : IDL.Func([IDL.Text], [], []),
  'updateServer' : IDL.Func([Server], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'serverId' : IDL.Text,
  });
  const Server = IDL.Record({
    'id' : IDL.Text,
    'ip' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'rating' : IDL.Nat,
    'ytVideoUrl' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'discordUrl' : IDL.Opt(IDL.Text),
    'version' : IDL.Opt(IDL.Text),
    'maxPlayers' : IDL.Opt(IDL.Nat),
    'location' : IDL.Opt(IDL.Text),
    'gameMode' : IDL.Opt(IDL.Text),
    'status' : IDL.Opt(IDL.Text),
  });
  const SiteSettings = IDL.Record({ 'heroSubtitle' : IDL.Text });
  
  return IDL.Service({
    'addReview' : IDL.Func([Review], [], []),
    'addServer' : IDL.Func([Server], [], []),
    'deleteReview' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteServer' : IDL.Func([IDL.Text], [], []),
    'getAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
    'getLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'saveSiteSettings' : IDL.Func([SiteSettings], [], []),
    'seedSampleServers' : IDL.Func([], [], []),
    'setAnnouncement' : IDL.Func([IDL.Text], [], []),
    'updateServer' : IDL.Func([Server], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
