/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SiteSettings {
    heroSubtitle: string;
}
export interface Review {
    id: string;
    date: string;
    name: string;
    text: string;
    serverId: string;
}
export interface Server {
    id: string;
    ip: string;
    name: string;
    createdAt: string;
    tags: Array<string>;
    description: [] | [string];
    imageUrl: string;
    rating: bigint;
    ytVideoUrl: [] | [string];
    website: [] | [string];
    discordUrl: [] | [string];
    version: [] | [string];
    maxPlayers: [] | [bigint];
    location: [] | [string];
    gameMode: [] | [string];
    status: [] | [string];
}
export interface backendInterface {
    addReview(review: Review): Promise<void>;
    addServer(server: Server): Promise<void>;
    deleteReview(serverId: string, reviewId: string): Promise<void>;
    deleteServer(id: string): Promise<void>;
    getAnnouncement(): Promise<string>;
    getLastUpdated(): Promise<bigint>;
    getReviews(serverId: string): Promise<Array<Review>>;
    getServers(): Promise<Array<Server>>;
    getSiteSettings(): Promise<SiteSettings>;
    saveSiteSettings(settings: SiteSettings): Promise<void>;
    seedSampleServers(): Promise<void>;
    setAnnouncement(text: string): Promise<void>;
    updateServer(server: Server): Promise<void>;
}
import type { Server as _Server } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addServer(arg0: Server): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addServer(to_candid_Server_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServer(to_candid_Server_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteReview(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0, arg1);
            return result;
        }
    }
    async deleteServer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServer(arg0);
            return result;
        }
    }
    async getAnnouncement(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncement();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncement();
            return result;
        }
    }
    async getLastUpdated(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdated();
            return result;
        }
    }
    async getReviews(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getServers(): Promise<Array<Server>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServers();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServers();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async saveSiteSettings(arg0: SiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSiteSettings(arg0);
            return result;
        }
    }
    async seedSampleServers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleServers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleServers();
            return result;
        }
    }
    async setAnnouncement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAnnouncement(arg0);
            return result;
        }
    }
    async updateServer(arg0: Server): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServer(to_candid_Server_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServer(to_candid_Server_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Server_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Server): Server {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Server): Server {
    return {
        id: value.id,
        ip: value.ip,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        description: (value as any).description ?? [],
        imageUrl: value.imageUrl,
        rating: value.rating,
        ytVideoUrl: (value as any).ytVideoUrl ?? [],
        website: (value as any).website ?? [],
        discordUrl: (value as any).discordUrl ?? [],
        version: (value as any).version ?? [],
        maxPlayers: (value as any).maxPlayers ?? [],
        location: (value as any).location ?? [],
        gameMode: (value as any).gameMode ?? [],
        status: (value as any).status ?? [],
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Server>): Array<Server> {
    return value.map((x)=>from_candid_Server_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Server_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Server): _Server {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Server): _Server {
    return {
        id: value.id,
        ip: value.ip,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        imageUrl: value.imageUrl,
        rating: value.rating,
        ytVideoUrl: value.ytVideoUrl,
        website: value.website,
        discordUrl: value.discordUrl,
        version: value.version,
        maxPlayers: value.maxPlayers,
        location: value.location,
        gameMode: value.gameMode,
        status: value.status,
    } as unknown as _Server;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
